[build-system]
requires = [
    "robotpy-build",
    "robotpy-wpiutil"
]

[tool.robotpy-build]
base-package = "ntcore"

[tool.robotpy-build.wrappers."ntcore._impl"]

libname = "ntcore"
artname = "ntcore-cpp"
baseurl = "http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/ntcore"
version = "2019.4.1"

sources = [
    "ntcore/_impl/ntcore.cpp"
]

depends = ["wpiutil"]

generate = [
    { NetworkTable = "networktables/NetworkTable.h"},
    { NetworkTableEntry = "networktables/NetworkTableEntry.h"},
    { NetworkTableInstance = "networktables/NetworkTableInstance.h"},
    { NetworkTableType = "networktables/NetworkTableType.h"},
]

generation_data = "gen/data.yml"


[tool.robotpy-build.metadata]
name = "pyntcore"
description = "Binary wrappers for the FRC ntcore library"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/pyntcore"
license = "BSD-3-Clause"
